---
name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true

jobs:
  Release-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6

      - name: Create tag
        if: github.ref == 'refs/heads/Mainline'
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "v${{ github.event.inputs.version }}"

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.workspace }}/git-credential-outlook
            ${{ github.workspace }}/git-credential-gmail
            ${{ github.workspace }}/git-credential-yahoo
            ${{ github.workspace }}/git-credential-aol
            ${{ github.workspace }}/git-msgraph
            ${{ github.workspace }}/git-protonmail
          tag_name: "v${{ github.event.inputs.version }}"
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  Release-DEB:
    needs: [Release-GitHub]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6
        with:
          ref: v${{ github.event.inputs.version }}

      - name: Configure GPG Key
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Release
        id: publish
        run: |
          sudo apt update
          sudo apt install -y wget git gpg apt-utils dpkg-dev
          git checkout v${{ github.event.inputs.version }}
          cd ${{ github.workspace }}

          for i in git-credential-outlook git-credential-gmail git-credential-yahoo git-credential-aol git-msgraph git-protonmail
          do
            mkdir -p ${{ github.workspace }}/cred-$i/DEBIAN
            mkdir -p ${{ github.workspace }}/cred-$i/usr/bin
            cp ./$i ./cred-$i/usr/bin
          done

          cat <<EOF  > ./cred-git-credential-outlook/DEBIAN/control
          Package: git-credential-outlook
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-keyring, python3-requests
          Recommends: python3-qrcode
          Suggests: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git credential helper for Microsoft Outlook accounts
          EOF

          cat <<EOF  > ./cred-git-credential-gmail/DEBIAN/control
          Package: git-credential-gmail
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-keyring, python3-requests
          Recommends: python3-qrcode
          Suggests: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git credential helper for Gmail accounts
          EOF

          cat <<EOF  > ./cred-git-credential-yahoo/DEBIAN/control
          Package: git-credential-yahoo
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-keyring, python3-requests
          Recommends: python3-qrcode
          Suggests: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git credential helper for Yahoo accounts
          EOF

          cat <<EOF  > ./cred-git-credential-aol/DEBIAN/control
          Package: git-credential-aol
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-keyring, python3-requests
          Recommends: python3-qrcode
          Suggests: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git credential helper for AOL accounts
          EOF

          cat <<EOF  > ./cred-git-msgraph/DEBIAN/control
          Package: git-msgraph
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-keyring, python3-requests
          Recommends: python3-qrcode
          Suggests: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git helper to use Microsoft Graph API instead of SMTP to send emails
          EOF

          cat <<EOF  > ./cred-git-protonmail/DEBIAN/control
          Package: git-protonmail
          Version: ${{ github.event.inputs.version }}
          Section: utils
          Priority: optional
          Depends: git-email, python3-bcrypt, python3-cryptography, python3-keyring, python3-pgpy, python3-pyasn1, python3-requests, python3-requests-toolbelt, python3-typing-extensions
          Recommends: python3-pyqt6.qtwebengine | python3-pyside6.qtwebenginewidgets
          Enhances: git-email
          Architecture: all
          Maintainer: Aditya Garg <gargaditya08@live.com>
          Description: Git helper to use ProtonMail API to send emails
          EOF

          for i in git-credential-outlook git-credential-gmail git-credential-yahoo git-credential-aol git-msgraph git-protonmail
          do
            chmod a+x ./cred-$i/DEBIAN/control
            chmod a+x ./cred-$i/usr/bin/$i
            dpkg-deb --build --root-owner-group -Zgzip cred-$i
            dpkg-name cred-$i.deb
          done

          gh release download debian -D debian -R AdityaGarg8/git-credential-email
          mv -v ./*.deb ./debian
          cd debian
          dpkg-scanpackages --multiversion . > Packages
          gzip -k -f Packages

          apt-ftparchive release . > Release
          gpg --default-key "${GPG_SIGNING_EMAIL}" -abs -o - Release > Release.gpg
          gpg --default-key "${GPG_SIGNING_EMAIL}" --clearsign -o - Release > InRelease
          gh release upload debian ./* --clobber -R AdityaGarg8/git-credential-email
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}
          GH_TOKEN: ${{ secrets.PAT }}
  Release-RPM:
    needs: [Release-GitHub]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6

      - name: Release
        id: publish
        run: |
          cat <<EOF  > ./rpm/git-credential-outlook.spec
          Name:           git-credential-outlook
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git credential helper for Microsoft Outlook accounts

          License:        Apache-2.0
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-keyring
          Requires:       python-requests
          Recommends:     python-qrcode
          Suggests:       (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-keyring
          Requires:       python3-requests
          Recommends:     python3-qrcode
          Suggests:       (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif

          %description
          Git credential helper for Microsoft Outlook accounts.

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-credential-outlook %{buildroot}%{_bindir}/git-credential-outlook

          %files
          %license LICENSE-APACHE NOTICE
          %doc README.md
          %{_bindir}/git-credential-outlook
          EOF

          cat <<EOF  > ./rpm/git-credential-gmail.spec
          Name:           git-credential-gmail
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git credential helper for Gmail accounts

          License:        Apache-2.0
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-keyring
          Requires:       python-requests
          Recommends:     python-qrcode
          Suggests:       (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-keyring
          Requires:       python3-requests
          Recommends:     python3-qrcode
          Suggests:       (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif

          %description
          Git credential helper for Gmail accounts.

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-credential-gmail %{buildroot}%{_bindir}/git-credential-gmail

          %files
          %license LICENSE-APACHE NOTICE
          %doc README.md
          %{_bindir}/git-credential-gmail
          EOF

          cat <<EOF  > ./rpm/git-credential-yahoo.spec
          Name:           git-credential-yahoo
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git credential helper for Yahoo accounts

          License:        Apache-2.0
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-keyring
          Requires:       python-requests
          Recommends:     python-qrcode
          Suggests:       (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-keyring
          Requires:       python3-requests
          Recommends:     python3-qrcode
          Suggests:       (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif

          %description
          Git credential helper for Yahoo accounts.

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-credential-yahoo %{buildroot}%{_bindir}/git-credential-yahoo

          %files
          %license LICENSE-APACHE NOTICE
          %doc README.md
          %{_bindir}/git-credential-yahoo
          EOF

          cat <<EOF  > ./rpm/git-credential-aol.spec
          Name:           git-credential-aol
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git credential helper for AOL accounts

          License:        Apache-2.0
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-keyring
          Requires:       python-requests
          Recommends:     python-qrcode
          Suggests:       (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-keyring
          Requires:       python3-requests
          Recommends:     python3-qrcode
          Suggests:       (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif

          %description
          Git credential helper for AOL accounts.

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-credential-aol %{buildroot}%{_bindir}/git-credential-aol

          %files
          %license LICENSE-APACHE NOTICE
          %doc README.md
          %{_bindir}/git-credential-aol
          EOF

          cat <<EOF  > ./rpm/git-msgraph.spec
          Name:           git-msgraph
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git helper to use Microsoft Graph API instead of SMTP to send emails

          License:        Apache-2.0
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-keyring
          Requires:       python-requests
          Recommends:     python-qrcode
          Suggests:       (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-keyring
          Requires:       python3-requests
          Recommends:     python3-qrcode
          Suggests:       (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif

          %description
          Git helper to use Microsoft Graph API instead of SMTP to send emails

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-msgraph %{buildroot}%{_bindir}/git-msgraph

          %files
          %license LICENSE-APACHE NOTICE
          %doc README.md
          %{_bindir}/git-msgraph
          EOF

          cat <<EOF  > ./rpm/git-protonmail.spec
          Name:           git-protonmail
          Version:        ${{ github.event.inputs.version }}
          Release:        1%{?dist}
          Summary:        Git helper to use ProtonMail API to send emails

          License:        GPL-3.0-only
          URL:            https://github.com/AdityaGarg8/git-credential-email
          Source0:        %{url}/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz

          BuildArch:      noarch
          Requires:       git-email

          %if 0%{?fedora}%{?rhel}
          Requires:       python-bcrypt
          Requires:       python-cryptography
          Requires:       python-keyring
          Requires:       python-pgpy
          Requires:       python-pyasn1
          Requires:       python-requests
          Requires:       python-requests-toolbelt
          Requires:       python-typing-extensions
          Recommends:     (python-pyqt6-webengine or python-pyside6)
          %elif 0%{?suse_version}%{?sle_version}
          Requires:       python3-bcrypt
          Requires:       python3-cryptography
          Requires:       python3-keyring
          Requires:       python3-pgpy
          Requires:       python3-pyasn1
          Requires:       python3-requests
          Requires:       python3-requests-toolbelt
          Requires:       python3-typing-extensions
          Recommends:     (python3-PyQt6-WebEngine or python3-pyside6)
          %else
          %{error: unsupported distribution}
          %endif
          
          %description
          Git helper to use ProtonMail API to send emails

          %prep
          %autosetup -n git-credential-email-${{ github.event.inputs.version }}

          %build

          %install
          install -D -m0755 git-protonmail %{buildroot}%{_bindir}/git-protonmail

          %files
          %license LICENSE-GPL3
          %doc README.md
          %{_bindir}/git-protonmail
          EOF

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull
          git add .
          git commit -m "Update RPM packages to ${{ github.event.inputs.version }}" || true
      - name: Push changes to the repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - name: "Trigger COPR webhook"
        run: |
          for i in git-credential-outlook git-credential-gmail git-credential-yahoo git-credential-aol git-msgraph git-protonmail
          do
            curl -sS -X POST $COPR_WEBHOOK/$i
          done
        env:
          COPR_WEBHOOK: ${{ secrets.COPR_WEBHOOK }}
  Release-Archlinux:
    needs: [Release-GitHub]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6
        with:
          ref: v${{ github.event.inputs.version }}

      - name: Release
        id: publish
        run: |
          echo -n "$GPG_SIGNING_KEY" | base64 -di > key
          docker pull archlinux:latest
          docker run \
            -e GPG_SIGNING_EMAIL=${{ secrets.GPG_SIGNING_EMAIL }} \
            -e GH_TOKEN=${{ secrets.PAT }} \
            -e VER=${{ github.event.inputs.version }} \
            -t \
            -v "$(pwd)":/repo \
            archlinux:latest \
            /bin/bash -c 'pacman -Syu --noconfirm --needed sudo git base-devel wget github-cli && \
            mkdir /build && \
            mkdir /release && \
            useradd builduser -m && chown -R builduser:builduser /build && passwd -d builduser && \
            printf "builduser ALL=(ALL) ALL\n" | tee -a /etc/sudoers && \
            cp -r /repo/* /build && cat /repo/key | gpg --import && \
            cd /build && \


            echo "pkgname=git-credential-outlook" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git credential helper for Microsoft Outlook accounts\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"Apache-2.0\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-keyring\" \"python-requests\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier OAuth2 flow\" \"python-qrcode: To generate QR codes of important URLs\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            echo "pkgname=git-credential-gmail" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git credential helper for Gmail accounts\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"Apache-2.0\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-keyring\" \"python-requests\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier OAuth2 flow\" \"python-qrcode: To generate QR codes of important URLs\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            echo "pkgname=git-credential-yahoo" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git credential helper for Yahoo accounts\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"Apache-2.0\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-keyring\" \"python-requests\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier OAuth2 flow\" \"python-qrcode: To generate QR codes of important URLs\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            echo "pkgname=git-credential-aol" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git credential helper for AOL accounts\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"Apache-2.0\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-keyring\" \"python-requests\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier OAuth2 flow\" \"python-qrcode: To generate QR codes of important URLs\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            echo "pkgname=git-msgraph" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git helper to use Microsoft Graph API instead of SMTP to send emails\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"Apache-2.0\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-keyring\" \"python-requests\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier OAuth2 flow\" \"python-qrcode: To generate QR codes of important URLs\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            echo "pkgname=git-protonmail" > PKGBUILD && \
            echo "pkgver=${VER}" >> PKGBUILD && \
            echo "pkgrel=1" >> PKGBUILD && \
            echo "pkgdesc=\"Git helper to use ProtonMail API to send emails\"" >> PKGBUILD && \
            echo "arch=(\"any\")" >> PKGBUILD && \
            echo "url=\"https://github.com/AdityaGarg8/git-credential-email\"" >> PKGBUILD && \
            echo "license=(\"GPL-3.0-only\")" >> PKGBUILD && \
            echo "depends=(\"git\" \"perl-authen-sasl\" \"perl-io-socket-ssl\" \"python-bcrypt\" \"python-cryptography\" \"python-keyring\" \"python-pgpy\" \"python-pyasn1\" \"python-requests\" \"python-requests-toolbelt\" \"python-typing_extensions\")" >> PKGBUILD && \
            echo "optdepends=(\"python-pyqt6-webengine: For easier manual CAPTCHA solving\")" >> PKGBUILD && \
            echo "source=(\"\$pkgname\")" >> PKGBUILD && \
            echo "sha256sums=(\"SKIP\")" >> PKGBUILD && \
            echo "package() {" >> PKGBUILD && \
            echo "    install -Dm755 \"\$srcdir/\$pkgname\" \"\$pkgdir/usr/bin/\$pkgname\"" >> PKGBUILD && \
            echo "}" >> PKGBUILD && \
            sudo -u builduser makepkg --nodeps && \

            cp -v ./*pkg.tar.zst /release && \
            cd /release && \
            gpg --detach-sign --use-agent --yes git-credential-outlook*pkg.tar.zst && \
            gpg --detach-sign --use-agent --yes git-credential-gmail*pkg.tar.zst && \
            gpg --detach-sign --use-agent --yes git-credential-yahoo*pkg.tar.zst && \
            gpg --detach-sign --use-agent --yes git-credential-aol*pkg.tar.zst && \
            gpg --detach-sign --use-agent --yes git-msgraph*pkg.tar.zst && \
            gpg --detach-sign --use-agent --yes git-protonmail*pkg.tar.zst && \
            repo-add git-credential-email.db.tar.gz *pkg.tar.zst --sign && cd / && \
            gh release download archlinux -D archlinux -R AdityaGarg8/git-credential-email && \
            cp -v /release/* ./archlinux && cd ./archlinux && \
            gh release upload archlinux ./* --clobber -R AdityaGarg8/git-credential-email'
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  Release-Homebrew:
    needs: [Release-GitHub]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6

      - name: Get SHA256SUM
        id: compute_sha
        run: |
          wget https://github.com/AdityaGarg8/git-credential-email/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz
          SHASUM=$(sha256sum ./v${{ github.event.inputs.version }}.tar.gz | cut -d " " -f 1 | xargs)
          echo "sha=$SHASUM" >> $GITHUB_ENV

      - name: Release
        id: publish
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git clone https://github.com/AdityaGarg8/homebrew-git-credential-email
          cd homebrew-git-credential-email
          sed -i -E \
          -e 's|url "https://github.com/AdityaGarg8/git-credential-email/archive/refs/tags/v[0-9]+(\.[0-9]+)+\.tar\.gz"|url "https://github.com/AdityaGarg8/git-credential-email/archive/refs/tags/v${{ github.event.inputs.version }}.tar.gz"|' \
          -e '0,/sha256 "[a-f0-9]{64}"/s//sha256 "${{ env.sha }}"/' \
          git-credential-outlook.rb git-credential-gmail.rb git-credential-yahoo.rb git-credential-aol.rb git-msgraph.rb git-protonmail.rb
          cd ..
          
      - name: Publish to repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: 'homebrew-git-credential-email'
          destination-github-username: 'AdityaGarg8'
          destination-repository-name: 'homebrew-git-credential-email'
          user-email: github-actions[bot]@users.noreply.github.com
          user-name: github-actions[bot]
          target-branch: main
          commit-message: Update credential helpers to v${{ github.event.inputs.version }}
  Release-Windows:
    needs: [Release-GitHub]
    runs-on: windows-latest
    steps:
      - name: "Checkout Repo"
        uses: actions/checkout@v6

      - name: Release
        id: publish
        run: |
          New-Item -ItemType Directory -Path outlook
          New-Item -ItemType Directory -Path gmail
          New-Item -ItemType Directory -Path yahoo
          New-Item -ItemType Directory -Path aol
          New-Item -ItemType Directory -Path msgraph
          New-Item -ItemType Directory -Path protonmail
          New-Item -ItemType Directory -Path protonmail_lite
          pip install pyinstaller keyring requests qrcode
          Copy-Item -Path .\git-credential-outlook -Destination .\outlook
          Copy-Item -Path .\git-credential-gmail -Destination .\gmail
          Copy-Item -Path .\git-credential-yahoo -Destination .\yahoo
          Copy-Item -Path .\git-credential-aol -Destination .\aol
          Copy-Item -Path .\git-msgraph -Destination .\msgraph
          Copy-Item -Path .\git-protonmail -Destination .\protonmail
          Copy-Item -Path .\git-protonmail -Destination .\protonmail_lite
          cd outlook
          pyinstaller git-credential-outlook --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gco-resources
          cd ..
          cd gmail
          pyinstaller git-credential-gmail --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gcg-resources
          cd ..
          cd yahoo
          pyinstaller git-credential-yahoo --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gcy-resources
          cd ..
          cd aol
          pyinstaller git-credential-aol --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gca-resources
          cd ..
          cd msgraph
          pyinstaller git-msgraph --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gcm-resources
          cd ..

          pip install bcrypt cryptography keyring PGPy13 requests requests-toolbelt typing-extensions

          cd protonmail_lite
          pyinstaller git-protonmail --exclude-module PyQt6 --exclude-module PySide6 --icon=NONE --contents-directory gcpl-resources
          cd ..

          pip install PyQt6-WebEngine
          cd protonmail
          pyinstaller git-protonmail --exclude-module PySide6 --icon=NONE --contents-directory gcp-resources
          cd ..

          Compress-Archive -Path .\outlook\dist\git-credential-outlook\* -DestinationPath git-credential-outlook_win64.zip
          Compress-Archive -Path .\gmail\dist\git-credential-gmail\* -DestinationPath git-credential-gmail_win64.zip
          Compress-Archive -Path .\yahoo\dist\git-credential-yahoo\* -DestinationPath git-credential-yahoo_win64.zip
          Compress-Archive -Path .\aol\dist\git-credential-aol\* -DestinationPath git-credential-aol_win64.zip
          Compress-Archive -Path .\msgraph\dist\git-msgraph\* -DestinationPath git-msgraph_win64.zip
          Compress-Archive -Path .\protonmail\dist\git-protonmail\* -DestinationPath git-protonmail_win64.zip
          Compress-Archive -Path .\protonmail_lite\dist\git-protonmail\* -DestinationPath git-protonmail_lite_win64.zip

      - name: Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ${{ github.workspace }}/*.zip
          tag_name: "v${{ github.event.inputs.version }}"
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
